### ISSUE TITLE
Error with adding new elements in dictionary

### ISSUE THREAD

**Issue by ghost** [TehCheat/PoEHUD#302] opened 2018-07-23 11:08 UTC
![image](https://user-images.githubusercontent.com/38328226/43073223-972371ac-8e9a-11e8-9d3e-426e2fca57e6.png)
After running
Translate: Elelment with this key already added to the dictionary.
All requirements installed.
How to solve this?

**Comment by TriTriTri1** [comment] 2018-07-26 22:12
Hi,
I see that issue is closed, but I am still having same issue. What was the solution?

Thanks

**Comment by TehCheat** [comment] 2018-07-27 00:50
@TriTriTri1 That issue is closed because this one is the same error and was created first. If people could read, they wouldn't open duplicate issues and they wouldn't get their issues closed.

**Comment by danielwerner-dev** [comment] 2018-07-27 01:19
Any tips of how to solve this problem ?

**Comment by danielwerner-dev** [comment] 2018-07-27 17:49
Any tips of how to solve this problem ?

**Comment by TehCheat** [comment] 2018-07-27 18:06
The tip is get the proper offsets and build the project.

**Comment by danielwerner-dev** [comment] 2018-07-27 18:07
How can i do it? If i cant do, will be released a new version ?

**Comment by TehCheat** [comment] 2018-07-27 18:14
If you don't know how to get and updates yourself, you'll have to wait for someone to update it for you. I'll get to it when I have time.

**Comment by danielwerner-dev** [comment] 2018-07-30 19:38
There is any paid version of this software to get it functional asap ?

**Comment by TehCheat** [comment] 2018-07-30 19:45
From what I saw there were 3 big things that broke. I have 2 fixed locally and the third should not take me long. Perhaps there will be more smaller things broken that I'll run into after I get that fixed, but I saw hud working when I bypassed the 3rd one last night.

**Comment by danielwerner-dev** [comment] 2018-07-30 19:47
Thas sounds good man, i was thinking something about that, big chances or problems to get solved that were taking so many time. Any date to release one new version ?

**Comment by TehCheat** [comment] 2018-07-30 19:57
I stated in the OC thread that I should have something today.

**Comment by danielwerner-dev** [comment] 2018-07-30 20:07
Thanks man, im new here, and to be honest, i dont know where is the OC thread, thats why i re-asked here. Sorry for that

**Comment by danielwerner-dev** [comment] 2018-07-30 21:33
When a new release comes, will be viewed here: https://github.com/TehCheat/PoEHUD/releases ?

**Comment by TehCheat** [comment] 2018-07-30 23:07
Generally speaking, no. It usually shows up as a new commit on the project. When I'm comfortable with a build, it gets released. Sometimes that's several days after changes are made.

**Comment by TehCheat** [comment] 2018-08-07 20:11
Is this still happening or can this be closed? I was fairly certain this was happening because the game state controller pattern was bad, but it has since been fixed.

**Comment by danielwerner-dev** [comment] 2018-08-07 20:14
I've updated my version last nigth, and it was crashing with flaskmanager, but re-openning hud all works well, until crashes again. So its a circle: open->crash->close->open->repeat

As i'm working now, i cant send the error message, but when i'm in home, i'll send you.

**Comment by danielwerner-dev** [comment] 2018-08-07 20:14
But the original error was solved :)

**Comment by danielwerner-dev** [comment] 2018-08-07 20:16
Im new with HUD, im afraid with bans, but i just use it to auto-flask, i dont use any other thing of it. I think they have sent that warns to people that was using bots, dont you think ?

**Comment by danielwerner-dev** [comment] 2018-08-07 22:22
Its 100% confirmed, the new version with area map fox it's crashing with flaskmanager.

**Comment by danielwerner-dev** [comment] 2018-08-07 22:31
![screenshot_1](https://user-images.githubusercontent.com/16060848/43806015-81a86bc2-9a78-11e8-97f7-2ee7a436d975.png)

**Comment by zaafar** [comment] 2018-08-08 00:11
This flask manager is old and isn’t supported anymore. I don’t think so there is anything poehud can do about that.

**Closed as completed** 2018-08-08 00:12 UTC
